#pragma once

enum class TokenType
{
    TOKEN_KEYWORD,
    TOKEN_IDENTIFIER,
    TOKEN_INTEGER_LITERAL,
    TOKEN_FLOAT_LITERAL,
    TOKEN_BOOL_LITERAL,
    TOKEN_STRING_LITERAL,
    TOKEN_SINGLE_QUOTE,
    TOKEN_DOUBLE_QUOTE,
    TOKEN_LEFT_PARENTHESIS,
    TOKEN_RIGHT_PARENTHESIS,
    TOKEN_LEFT_BRACE,
    TOKEN_COMMA,
    TOKEN_RIGHT_BRACE,
    TOKEN_LEFT_BRACKET,
    TOKEN_EQUALITY_OPERATOR,
    TOKEN_NOT_EQUALITY_OPERATOR,
    TOKEN_NOT_OPERATOR,
    TOKEN_RIGHT_BRACKET,
    TOKEN_SEMICOLON,
    TOKEN_LAZY_RETURN_OPERATOR,
    TOKEN_MODULE_NAMESPACE_CROSS_OPERATOR,
    TOKEN_METHOD_MEMBER_ACCESS_OPERATOR,
    TOKEN_CHAIN_OPERATOR,
    TOKEN_ASSIGNMENT_OPERATOR,
    TOKEN_PLUS_OPERATOR,
    TOKEN_MINUS_OPERATOR,
    TOKEN_STAR_OPERATOR,
    TOKEN_DIVISION_OPERATOR,
    TOKEN_GREATER_THAN_OPERATOR,
    TOKEN_LESS_THAN_OPERATOR,
    TOKEN_GREATER_THAN_OR_EQUAL_OPERATOR,
    TOKEN_LESS_THAN_OR_EQUAL_OPERATOR,
    TOKEN_NULLABLE_OPERATOR,
    TOKEN_NULL_COALESCING_OPERATOR,
    TOKEN_COMPOUND_ADD_OPERATOR,
    TOKEN_COMPOUND_SUBTRACT_OPERATOR,
    TOKEN_COMPOUND_MULTIPLY_OPERATOR,
    TOKEN_COMPOUND_DIVIDE_OPERATOR,
    TOKEN_INCREMENT_OPERATOR,
    TOKEN_DECREMENT_OPERATOR,
    TOKEN_IF,
    TOKEN_ELSE,
    TOKEN_FOR,
    TOKEN_WHILE,
    TOKEN_RETURN,
    TOKEN_BREAK,
    TOKEN_CONTINUE,
    TOKEN_AMPERSAND_OPERATOR,
    TOKEN_END_OF_FILE
};

struct Token
{
    TokenType type;
    std::string value;
    uint64_t line;
};