# embed_binary.cmake — converts a binary file to a C header with a const array.
# Usage:
#   cmake -DBIN_FILE=<path> -DOUT_FILE=<path> -DVARIABLE_NAME=<name> -P embed_binary.cmake
#
# Produces a header containing:
#   static const unsigned char <VARIABLE_NAME>[] = { ... };
#   static const unsigned int  <VARIABLE_NAME>_size = sizeof(<VARIABLE_NAME>);

file(READ "${BIN_FILE}" RAW_CONTENT HEX)
# Insert "0x" prefix and comma after every two hex digits
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," HEX_BYTES "${RAW_CONTENT}")
# Remove trailing comma
string(REGEX REPLACE ",$" "" HEX_BYTES "${HEX_BYTES}")

set(CONTENT
    "#pragma once\n/* Auto-generated by cmake/embed_binary.cmake -- DO NOT EDIT */\nstatic const unsigned char ${VARIABLE_NAME}[] = { ${HEX_BYTES} };\nstatic const unsigned int  ${VARIABLE_NAME}_size = sizeof(${VARIABLE_NAME});\n"
)
file(WRITE "${OUT_FILE}" "${CONTENT}")
